- platform: mqtt_json
  name: "Living Room LED Strip"
  state_topic: "home/ESP_LED"
  command_topic: "home/ESP_LED/set"
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0
